import React from 'react';
import { ArrowLeft, Shield } from 'lucide-react';

/**
 * Public privacy notice — the in-app rendering of
 * docs/compliance/privacy-notice.md (v1.0, 2026-08-07).
 *
 * KEEP IN SYNC: the markdown file is the reviewed source of truth; edit it
 * first, then mirror here and bump the version stamp below. The [DECIDE]
 * markers in the doc are resolved here to their working values (entity
 * "Relantern", contact privacy@relantern.com) — if the legal-entity pass
 * changes those, both files change together.
 */

const Section: React.FC<{ n: string; title: string; children: React.ReactNode }> = ({ n, title, children }) => (
    <section className="mb-8">
        <h2 className="text-[17px] font-extrabold tracking-tight mb-3" style={{ color: '#1e293b' }}>
            {n}. {title}
        </h2>
        <div className="space-y-3 text-[14px] leading-relaxed font-medium" style={{ color: '#475569' }}>
            {children}
        </div>
    </section>
);

export const Privacy: React.FC = () => {
    return (
        <div className="min-h-screen" style={{ background: '#f8fafc' }}>
            {/* Header — same visual language as Login */}
            <header className="sticky top-0 z-20 px-5 sm:px-8 py-4 flex items-center justify-between"
                    style={{ background: 'rgba(248, 250, 252, 0.9)', backdropFilter: 'blur(8px)', borderBottom: '1px solid #e2e8f0' }}>
                <div className="flex items-center gap-3">
                    <div className="w-9 h-9 rounded-xl flex items-center justify-center"
                         style={{ background: 'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)', boxShadow: '0 2px 8px rgba(245, 158, 11, 0.3)' }}>
                        <Shield size={17} color="white" strokeWidth={2.5} />
                    </div>
                    <div>
                        <div className="text-[17px] font-extrabold tracking-tight" style={{ color: '#1e293b' }}>Privacy Notice</div>
                        <div className="text-[9px] font-semibold uppercase tracking-[0.12em]" style={{ color: '#94a3b8' }}>IREAMS by Relantern</div>
                    </div>
                </div>
                <a href="/login" className="flex items-center gap-1.5 text-[13px] font-bold px-4 py-2 rounded-lg transition-colors"
                   style={{ color: '#f59e0b', border: '1.5px solid #fde68a', background: '#fffbeb' }}>
                    <ArrowLeft size={14} /> Back to sign in
                </a>
            </header>

            <main className="max-w-[760px] mx-auto px-5 sm:px-8 py-10">
                <p className="text-[12px] font-semibold mb-8" style={{ color: '#94a3b8' }}>
                    Version 1.0 · 7 August 2026 · Contact: <a href="mailto:privacy@relantern.com" className="underline" style={{ color: '#f59e0b' }}>privacy@relantern.com</a>
                </p>

                <div className="rounded-2xl p-7 sm:p-10"
                     style={{ background: '#ffffff', border: '1px solid #e2e8f0', boxShadow: '0 4px 24px rgba(148, 163, 184, 0.1)' }}>

                    <p className="text-[14px] leading-relaxed font-medium mb-8" style={{ color: '#475569' }}>
                        This notice explains what personal data IREAMS processes, why, and what
                        rights you have. It is written for two kinds of people:{' '}
                        <strong style={{ color: '#334155' }}>workspace users</strong>, who use IREAMS because their
                        employer (our customer) gave them an account — for that data the employer is the
                        controller and Relantern is the processor, acting on their instructions — and{' '}
                        <strong style={{ color: '#334155' }}>account owners</strong>, who signed up for a workspace
                        themselves — for signup and account data Relantern is the controller.
                    </p>

                    <Section n="1" title="What we collect">
                        <p><strong style={{ color: '#334155' }}>At signup:</strong> company name, your work email address, and a
                        password (stored only as a salted hash by our authentication provider).</p>
                        <p><strong style={{ color: '#334155' }}>In your workspace:</strong> the people directory your organisation
                        maintains — name, work email, phone, job title, department, work location,
                        hourly rate where your employer records it, profile photo if you upload one,
                        and qualification records including scanned certificates.</p>
                        <p><strong style={{ color: '#334155' }}>Generated by using the product:</strong> work orders, service
                        requests, readings and inspections you create or are assigned; hand-drawn
                        sign-off signatures on job safety analyses; messages and mentions in record
                        threads; notifications addressed to you; an append-only audit trail recording
                        who changed what and when; invitation links sent to your email or phone.</p>
                        <p><strong style={{ color: '#334155' }}>Technical:</strong> authentication tokens in your browser's local
                        storage (strictly necessary, not tracking), timestamps, and server logs at our
                        infrastructure providers.</p>
                        <p>We do <strong style={{ color: '#334155' }}>not</strong> collect browsing history or advertising
                        identifiers, and we run no third-party analytics or tracking cookies.</p>
                    </Section>

                    <Section n="2" title="What we use it for">
                        <p>Operating your workspace (accounts, assignments, notifications, audit
                        trail) on the basis of contract, or your employer's instructions; sending
                        operational email — invites, notifications, digests — never marketing without
                        separate consent; AI-assisted analysis as described in section 4; security,
                        access control and abuse prevention as a legitimate interest and a legal
                        obligation; and safety records (sign-offs, permits) supporting your employer's
                        occupational-safety obligations.</p>
                    </Section>

                    <Section n="3" title="Where your data lives">
                        <p>The production database, file storage, and authentication run on Supabase
                        hosted in AWS eu-west-1 (Ireland) — your data at rest stays in the EU. The web
                        application is served by Vercel's global edge network (the application code,
                        not your database contents). Email is dispatched via Resend from
                        mail.relantern.com. A full sub-processor list is available on request via the
                        privacy contact.</p>
                    </Section>

                    <Section n="4" title="AI features — what leaves the workspace">
                        <p>Some features send data to Google's Gemini API to generate analysis: when
                        you ask the assistant a question or run an AI analysis, the text of your
                        question plus relevant record context (for example work-order descriptions and
                        asset data) is transmitted to Google and the response returned. Free-text
                        fields may incidentally contain personal data, such as a technician named in a
                        work-order note.</p>
                        <p>AI calls are made server-side through an authenticated proxy — your
                        credentials are never shared with Google — and usage is metered per workspace.
                        If your organisation does not want record data reaching an AI provider, the AI
                        features can be disabled for your workspace on request.</p>
                    </Section>

                    <Section n="5" title="How long we keep it">
                        <p>Workspace data is kept while your employer's contract runs and deleted or
                        returned at termination. Account data is kept while your account exists. Audit
                        trails are retained as integrity records, but the person reference in them is
                        pseudonymised when a person is erased. Engineering records about equipment are
                        kept as long as the workspace wants them.</p>
                    </Section>

                    <Section n="6" title="Who can see it">
                        <p>Access is enforced in the database, per row: users see only their own
                        company's workspace, and within it only what their role permits. Photos,
                        documents and signatures are private and served only via short-lived signed
                        links to authenticated members of the same workspace. Relantern staff access
                        production only for support and operations. We do not sell personal data.</p>
                    </Section>

                    <Section n="7" title="Your rights">
                        <p>Under GDPR you can request access, rectification, erasure, restriction,
                        portability, and object to processing. If you use IREAMS through your
                        employer, direct requests to your employer first — we support them on their
                        instruction. If you own the account, email{' '}
                        <a href="mailto:privacy@relantern.com" className="underline" style={{ color: '#f59e0b' }}>privacy@relantern.com</a>;
                        we respond within one month. You may also complain to your data-protection
                        supervisory authority.</p>
                    </Section>

                    <Section n="8" title="Changes">
                        <p>Material changes to this notice are announced in-app and dated at the top
                        of this page.</p>
                    </Section>
                </div>
            </main>
        </div>
    );
};
