apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    release: {{ .Release.Name }}
data:
  REDIS_URL: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
  {{- range $key, $val := .Values.featureFlags }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
