-- 0094_extend_org_hierarchy.sql
-- ============================================================
-- Extend Organization Hierarchy: Support dynamic level types
-- 1. Drop restrictive CHECK constraint on organization_units.type
-- 2. Seed 4 default ORG_LEVEL dictionary entries
-- ============================================================

-- STEP 1: Drop CHECK constraint (if it exists from migration 0020)
-- The constraint name is auto-generated by Postgres as <table>_<column>_check
DO $$
DECLARE
    constraint_name TEXT;
BEGIN
    SELECT con.conname INTO constraint_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE rel.relname = 'organization_units'
      AND con.contype = 'c'
      AND nsp.nspname = 'public'
    LIMIT 1;

    IF constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE organization_units DROP CONSTRAINT %I', constraint_name);
        RAISE NOTICE 'Dropped CHECK constraint: %', constraint_name;
    ELSE
        RAISE NOTICE 'No CHECK constraint found on organization_units.type — already flexible.';
    END IF;
END $$;

-- STEP 2: Seed default ORG_LEVEL dictionary entries
-- Division → Department → Unit → Team
INSERT INTO reference_codes (category, code, description, active, sort_order, metadata, color_code)
VALUES
    ('ORG_LEVEL', 'DIVISION', 'Division', true, 1,
     '{"sort_order": 1, "child_type": "DEPARTMENT"}'::jsonb, '#3b82f6'),
    ('ORG_LEVEL', 'DEPARTMENT', 'Department', true, 2,
     '{"sort_order": 2, "child_type": "UNIT"}'::jsonb, '#8b5cf6'),
    ('ORG_LEVEL', 'UNIT', 'Unit', true, 3,
     '{"sort_order": 3, "child_type": "TEAM"}'::jsonb, '#f59e0b'),
    ('ORG_LEVEL', 'TEAM', 'Team', true, 4,
     '{"sort_order": 4, "child_type": null}'::jsonb, '#10b981')
ON CONFLICT DO NOTHING;

-- Ensure existing GROUP entries get updated (GROUP → DEPARTMENT rename)
-- Only update if GROUP still exists and DEPARTMENT doesn't
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM reference_codes WHERE category = 'ORG_LEVEL' AND code = 'GROUP'
    ) AND NOT EXISTS (
        SELECT 1 FROM reference_codes WHERE category = 'ORG_LEVEL' AND code = 'DEPARTMENT'
    ) THEN
        UPDATE reference_codes
        SET code = 'DEPARTMENT', description = 'Department',
            metadata = '{"sort_order": 2, "child_type": "UNIT"}'::jsonb
        WHERE category = 'ORG_LEVEL' AND code = 'GROUP';
        RAISE NOTICE 'Renamed GROUP → DEPARTMENT in ORG_LEVEL dictionaries';
    END IF;
END $$;
