-- ════════════════════════════════════════════════════════════════════════════
-- 0269 — G4 learns the difference between mentioning the tenant and enforcing it
--
-- tenancy_policy_gaps() (0264) asks whether a policy MENTIONS caller_company.
-- That was the right question when every tenant policy had the identical shape
-- `company_id = caller_company() AND <role test>`, generated by one loop.
--
-- 0267 broke that assumption on purpose. Config tables need to serve global
-- product defaults to everybody:
--
--     USING (company_id IS NULL OR company_id = (SELECT caller_company()))
--
-- which is correct — `company_id IS NULL` is the product's own row, deliberately
-- shared. But it means an OR is now a legitimate shape, and the check cannot
-- tell that one from:
--
--     USING (company_id = (SELECT caller_company()) OR true)
--
-- which mentions caller_company, passes G4, and is wide open. The gap was always
-- there; 0267 is what makes it reachable, because "policies have ORs now" is no
-- longer a red flag on its own.
--
-- ── Position, not presence ─────────────────────────────────────────────────
-- A tenant test only enforces anything if nothing can satisfy the expression
-- WITHOUT it. So the qual must start with the tenant test as a top-level
-- conjunct — or be one of the two shapes explicitly allowed here. Anything else
-- is reported, including shapes nobody has thought of yet, which is the point.
--
-- ── Parentheses have broken this exact check three times ───────────────────
-- Postgres re-renders quals with its own parenthesisation. A structural check
-- earlier in this workstream assumed one leading paren where it emits two and
-- reported 617 false violations. The first draft of THIS function assumed
-- `company_id IS NULL OR company_id = …` and Postgres actually writes
-- `((company_id IS NULL) OR (company_id = (…)))` — parens around each operand —
-- so it flagged all four config policies as broken.
--
-- Chasing the exact paren layout is a losing game. So: delete every paren and
-- collapse whitespace FIRST, then match against the paren-free form. The guard
-- at the bottom refuses to apply the migration if the matcher flags any of the
-- 480 policies already known to be correct.
-- ════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.tenancy_policy_gaps()
RETURNS TABLE (kind text, object_name text, detail text)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
    WITH tenant_tables AS (
        SELECT c.oid, c.relname
          FROM pg_class c
          JOIN pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = 'public'
           AND c.relkind = 'r'
           AND EXISTS (SELECT 1 FROM information_schema.columns col
                        WHERE col.table_schema = 'public'
                          AND col.table_name = c.relname
                          AND col.column_name = 'company_id')
           AND c.relname NOT IN ('users', 'companies')
    )
    -- (a) RLS off, or no policy at all: nothing to inspect, nothing to OR
    --     against — wide open and silent.
    SELECT 'rls_disabled'::text, t.relname::text,
           format('rls_enabled=%s policies=%s', c.relrowsecurity,
                  (SELECT count(*) FROM pg_policies p
                    WHERE p.schemaname = 'public' AND p.tablename = t.relname))
      FROM tenant_tables t
      JOIN pg_class c ON c.oid = t.oid
     WHERE c.relrowsecurity = false
        OR NOT EXISTS (SELECT 1 FROM pg_policies p
                        WHERE p.schemaname = 'public' AND p.tablename = t.relname)

    UNION ALL

    -- (b) a PERMISSIVE policy with no tenant test at all. Permissive policies
    --     OR together, so one bare policy defeats every sibling — the 0238 bug.
    SELECT 'policy_ungated'::text,
           format('%s.%s', p.tablename, p.policyname)::text,
           format('cmd=%s', p.cmd)
      FROM pg_policies p
      JOIN tenant_tables t ON t.relname = p.tablename
     WHERE p.schemaname = 'public'
       AND p.permissive = 'PERMISSIVE'
       AND coalesce(p.qual, '') || coalesce(p.with_check, '') NOT LIKE '%caller_company%'

    UNION ALL

    -- (c) NEW: the tenant test is present but not in enforcing position.
    --     Allowed shapes, compared with every paren removed:
    --       company_id = SELECT caller_company…                 the normal case
    --       company_id IS NULL OR company_id = SELECT caller…   config, 0267
    SELECT 'tenant_test_not_leading'::text,
           format('%s.%s', p.tablename, p.policyname)::text,
           format('cmd=%s expr=%s', p.cmd, left(e.flat, 90))
      FROM pg_policies p
      JOIN tenant_tables t ON t.relname = p.tablename
      CROSS JOIN LATERAL (
          SELECT coalesce(p.qual, p.with_check, '') AS expr,
                 btrim(regexp_replace(
                     regexp_replace(coalesce(p.qual, p.with_check, ''), '[()]', '', 'g'),
                     '\s+', ' ', 'g')) AS flat
      ) AS e
     WHERE p.schemaname = 'public'
       AND p.permissive = 'PERMISSIVE'
       AND e.expr LIKE '%caller_company%'
       AND e.flat !~ '^company_id (= SELECT caller_company|IS NULL OR company_id = SELECT caller_company)'

    UNION ALL

    -- (d) a view that reads past RLS with no tenant filter of its own.
    SELECT 'view_unfiltered'::text, c.relname::text,
           'definer view, no caller_company() filter'::text
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public'
       AND c.relkind = 'v'
       AND coalesce((SELECT option_value FROM pg_options_to_table(c.reloptions)
                      WHERE option_name = 'security_invoker'), 'false') <> 'true'
       AND pg_get_viewdef(c.oid, true) NOT LIKE '%caller_company%';
$$;

COMMENT ON FUNCTION public.tenancy_policy_gaps() IS
    'Static proof that the tenant boundary is complete AND enforcing. Checks RLS is on, every permissive policy carries a tenant test, that test is the LEADING top-level conjunct (so it cannot be OR-defeated), and no DEFINER view reads past RLS. Two leading shapes are allowed: the plain equality, and the 0267 config form that also serves global rows where company_id IS NULL. Called by tests/rls/tenant-completeness.mjs (gate G4).';

REVOKE ALL ON FUNCTION public.tenancy_policy_gaps() FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.tenancy_policy_gaps() TO service_role;

-- ── The matcher must not fire on what is already correct ───────────────────
-- 480 tenant policies exist and every one of them is known-good. If the new
-- rule flags any of them it is the rule that is wrong, and this migration must
-- not apply — a checker that cries wolf gets disabled, which is worse than not
-- having it.
DO $$
DECLARE n int; sample text;
BEGIN
    SELECT count(*), min(object_name) INTO n, sample
      FROM public.tenancy_policy_gaps() WHERE kind = 'tenant_test_not_leading';
    IF n > 0 THEN
        RAISE EXCEPTION 'new position check flags % existing policy(ies), e.g. % — the matcher is wrong, not the schema', n, sample;
    END IF;

    SELECT count(*) INTO n FROM public.tenancy_policy_gaps();
    IF n > 0 THEN
        RAISE EXCEPTION 'tenancy incomplete: % gap(s)', n;
    END IF;
    RAISE NOTICE 'position check added, 0 gaps';
END $$;
