-- ============================================================================
-- 0294 — sem_work_history learns the 0283 reliability columns
--
-- 0283 added the true failure-event data to work_orders (breakdown indicator,
-- actual labour hours, malfunction window) and the import chain now populates
-- them from foreign CMMS history (SAP Breakdown/MSAUS + Actual work, Maximo
-- ACTLABHRS). This exposes them through the semantic layer so analyses read
-- one canonical view instead of raw columns.
--
-- Columns are APPENDED (CREATE OR REPLACE VIEW requires the existing column
-- list to stay in place). NULL breakdown means "not recorded" — consumers
-- must not collapse it to false; the catalog entry says so.
--
-- Deliberately NOT touched (same stance as 0283): sem_work_orders (0233,
-- carries the 0261a DEFINER tenant patch) and sem_asset_reliability (0234a) —
-- adopting malfunction_start as the KPI event basis is the separate
-- KPI-unification pass.
-- ============================================================================

BEGIN;

CREATE OR REPLACE VIEW public.sem_work_history
WITH (security_invoker = true) AS
SELECT
  wo.id                    AS work_order_id,
  wo.wo_number,
  wo.title,
  wo.type                  AS work_type,
  wo.status::text          AS status,
  wo.priority_code,
  a.id                     AS asset_id,
  a.tag                    AS asset_tag,
  a.name                   AS asset_name,
  a.criticality::text      AS criticality,
  wc.code                  AS work_center_code,
  wo.recurring_work_id,    -- non-null ⇒ generated by a PM
  wo.request_id,           -- non-null ⇒ originated from a service request
  COALESCE(wo.frozen_labor_cost, 0)    AS labor_cost,
  COALESCE(wo.frozen_material_cost, 0) AS material_cost,
  COALESCE(wo.frozen_labor_cost, 0) + COALESCE(wo.frozen_material_cost, 0)
                           AS total_cost,
  wo.actual_downtime_hrs,
  wo.created_at,
  wo.due_date,
  wo.closed_at,
  -- 0283/0294: the real failure-event data.
  wo.breakdown,                              -- true = function lost; NULL = not recorded
  wo.actual_duration_hrs   AS labor_hours,   -- actual work hours at completion
  wo.malfunction_start,                      -- failure event time (SAP AUSVN)
  wo.malfunction_end                         -- back in service (SAP AUSBS)
FROM public.work_orders wo
JOIN public.assets a ON a.id = wo.asset_id
LEFT JOIN public.work_centers wc ON wc.id = wo.work_center_id;

-- ── Catalog annotations ────────────────────────────────────────────────────
INSERT INTO public.semantic_catalog
  (object_name, column_name, title, description, tags, owner, source_tables, iso_standard)
VALUES
  ('sem_work_history', 'breakdown', NULL,
   'Breakdown indicator (SAP MSAUS): true = the equipment lost its required function; false = recorded as non-failure work; NULL = not recorded. Prefer this over "type = CM" when counting failure events — not every corrective order is a functional failure. Never collapse NULL to false.',
   ARRAY['reliability','failures'], NULL, ARRAY['work_orders'], 'ISO 14224'),
  ('sem_work_history', 'labor_hours', NULL,
   'Order-level actual labour hours captured at completion (SAP "Actual work" / Maximo ACTLABHRS on import). Distinct from labor_cost. Powers maintainability (MTTR) and crew-load analysis.',
   ARRAY['maintenance','hours'], NULL, ARRAY['work_orders'], NULL),
  ('sem_work_history', 'malfunction_start', NULL,
   'Equipment malfunction start (SAP AUSVN; ISO 14224 failure event time). Preferred MTBF event basis over created_at, which is a paperwork date.',
   ARRAY['reliability','failures'], NULL, ARRAY['work_orders'], 'ISO 14224'),
  ('sem_work_history', 'malfunction_end', NULL,
   'Equipment back in service (SAP AUSBS). With malfunction_start, defines the true outage window; actual_downtime_hrs is derived from it when hours were not entered (0283 trigger).',
   ARRAY['reliability','availability'], NULL, ARRAY['work_orders'], 'ISO 14224')
ON CONFLICT (object_name, COALESCE(column_name, '·')) DO UPDATE
  SET description = EXCLUDED.description,
      tags        = EXCLUDED.tags,
      updated_at  = now();

COMMIT;

-- VERIFY (after apply):
--   SELECT breakdown, labor_hours, malfunction_start FROM sem_work_history LIMIT 1;
--   SELECT column_name FROM semantic_catalog WHERE object_name='sem_work_history';
