/**
 * Mock Asset Register — ISO 14224 compliant with equipment taxonomy.
 * Extracted from useAssets.ts for centralised management.
 * These are used when VITE_USE_MOCK is true or as seed-data templates.
 */
import type { Asset, HierarchyNode, FailureEvent } from '../types/assets';

const d = (daysAgo: number) => new Date(Date.now() - daysAgo * 86400000).toISOString();
const rpn = (c: number, p: number, det: number) => ({ rpn: c * p * det, consequence: c, probability: p, detectability: det });

export const MOCK_ASSETS: Asset[] = [
    // ── SITE A: Gas Processing ──
    { id: 'ast-k601', tag: 'K-601', name: 'Gas Compressor K-601', description: 'Centrifugal gas compressor, 1st stage compression', taxonomy_level: 'equipment', parent_id: 'sys-comp', site: 'Site A — Offshore Platform Alpha', unit: 'Gas Processing', system: 'Compression Train A', functional_location: 'ALPHA > GAS PROC > COMP-A', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'centrifugal_compressor', criticality: 'A', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'rcm', design_data: { rated_power_kw: 8500, design_pressure_bar: 85, design_temperature_c: 150, material_class: 'SS316', weight_kg: 12500 }, operating_context: { service_medium: 'Natural Gas', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(1825), warranty_expiry: d(-365), last_overhaul: d(180), condition_rating: 3, health_index: 82.5, rul_days: 142, risk_priority: rpn(5, 3, 2), running_hours: 42680, mtbf_days: 210, mttr_hours: 36, failure_count_ytd: 2, wo_count_ytd: 14, cost_ytd: 128500, manufacturer: 'Siemens', model: 'STC-SV', serial_number: 'SIE-K601-2021', children_count: 4 },

    { id: 'ast-k601-brg', tag: 'K-601-BRG', name: 'K-601 DE Bearing Assembly', description: 'Drive-end journal bearing, tilting pad', taxonomy_level: 'subunit', parent_id: 'ast-k601', site: 'Site A — Offshore Platform Alpha', unit: 'Gas Processing', system: 'Compression Train A', functional_location: 'ALPHA > GAS PROC > COMP-A > K-601', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'bearing_assembly', criticality: 'A', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'condition_based', install_date: d(1825), warranty_expiry: null, last_overhaul: d(180), condition_rating: 3, health_index: 74.0, rul_days: 95, risk_priority: rpn(5, 4, 2), running_hours: 42680, mtbf_days: null, mttr_hours: 24, failure_count_ytd: 1, wo_count_ytd: 4, cost_ytd: 32000, manufacturer: 'SKF', model: 'CARB C2226', serial_number: 'SKF-2226-8841', children_count: 0 },

    { id: 'ast-k601-seal', tag: 'K-601-SEAL', name: 'K-601 Dry Gas Seal', description: 'Primary dry gas seal assembly', taxonomy_level: 'subunit', parent_id: 'ast-k601', site: 'Site A — Offshore Platform Alpha', unit: 'Gas Processing', system: 'Compression Train A', functional_location: 'ALPHA > GAS PROC > COMP-A > K-601', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'dry_gas_seal', criticality: 'A', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'condition_based', install_date: d(730), warranty_expiry: d(-90), last_overhaul: null, condition_rating: 2, health_index: 58.0, rul_days: 65, risk_priority: rpn(5, 4, 3), running_hours: 17520, mtbf_days: null, mttr_hours: 48, failure_count_ytd: 0, wo_count_ytd: 3, cost_ytd: 18500, manufacturer: 'John Crane', model: 'Type 28AT', serial_number: 'JC-28AT-5512', children_count: 0 },

    { id: 'ast-gt301', tag: 'GT-301', name: 'Gas Turbine GT-301', description: 'Aeroderivative gas turbine generator, 25MW', taxonomy_level: 'equipment', parent_id: 'sys-power', site: 'Site A — Offshore Platform Alpha', unit: 'Power Generation', system: 'Main Power', functional_location: 'ALPHA > POWER GEN > MAIN', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'gas_turbine', criticality: 'A', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'rcm', design_data: { rated_power_kw: 25000, design_temperature_c: 1100, material_class: 'Inconel 718', weight_kg: 28000 }, operating_context: { service_medium: 'Natural Gas', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(2555), warranty_expiry: null, last_overhaul: d(365), condition_rating: 4, health_index: 91.2, rul_days: 280, risk_priority: rpn(5, 2, 2), running_hours: 58200, mtbf_days: 365, mttr_hours: 72, failure_count_ytd: 1, wo_count_ytd: 8, cost_ytd: 245000, manufacturer: 'GE Vernova', model: 'LM2500+', serial_number: 'GE-LM25-7422', children_count: 6 },

    { id: 'ast-p101', tag: 'P-101A', name: 'Centrifugal Pump P-101A', description: 'Crude oil export pump, API 610', taxonomy_level: 'equipment', parent_id: 'sys-export', site: 'Site A — Offshore Platform Alpha', unit: 'Crude Oil Processing', system: 'Export System', functional_location: 'ALPHA > CRUDE > EXPORT', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'centrifugal_pump', criticality: 'A', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'rcm', design_data: { rated_power_kw: 500, design_pressure_bar: 45, design_temperature_c: 80, material_class: 'Duplex SS', weight_kg: 3200 }, operating_context: { service_medium: 'Crude Oil', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(1460), warranty_expiry: null, last_overhaul: d(90), condition_rating: 4, health_index: 88.7, rul_days: 220, risk_priority: rpn(4, 2, 2), running_hours: 34500, mtbf_days: 280, mttr_hours: 18, failure_count_ytd: 0, wo_count_ytd: 6, cost_ytd: 42000, manufacturer: 'Sulzer', model: 'MSD-D 8x14', serial_number: 'SUL-MSD-3391', children_count: 3 },

    { id: 'ast-p102', tag: 'P-102', name: 'Booster Pump P-102', description: 'Water injection booster pump', taxonomy_level: 'equipment', parent_id: 'sys-wi', site: 'Site A — Offshore Platform Alpha', unit: 'Water Injection', system: 'Injection System', functional_location: 'ALPHA > WATER INJ > BOOST', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'centrifugal_pump', criticality: 'B', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'pm_optimization', design_data: { rated_power_kw: 350, design_pressure_bar: 200, design_temperature_c: 40, material_class: 'Super Duplex', weight_kg: 2400 }, operating_context: { service_medium: 'Treated Seawater', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(1095), warranty_expiry: null, last_overhaul: d(60), condition_rating: 2, health_index: 64.2, rul_days: 58, risk_priority: rpn(3, 4, 3), running_hours: 25600, mtbf_days: 120, mttr_hours: 12, failure_count_ytd: 3, wo_count_ytd: 11, cost_ytd: 67800, manufacturer: 'Flowserve', model: 'HPX 6000', serial_number: 'FS-HPX-8812', children_count: 2 },

    { id: 'ast-hx105', tag: 'HX-105', name: 'Overhead Condenser HX-105', description: 'Shell & tube condenser, crude distillation overhead', taxonomy_level: 'equipment', parent_id: 'sys-dist', site: 'Site A — Offshore Platform Alpha', unit: 'Crude Distillation', system: 'Overhead System', functional_location: 'ALPHA > CRUDE DIST > OVERHEAD', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'shell_and_tube', criticality: 'B', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'rbi', install_date: d(2190), warranty_expiry: null, last_overhaul: d(540), condition_rating: 3, health_index: 76.5, rul_days: 180, risk_priority: rpn(3, 3, 2), running_hours: 52000, mtbf_days: null, mttr_hours: 96, failure_count_ytd: 0, wo_count_ytd: 3, cost_ytd: 15200, manufacturer: 'Alfa Laval', model: 'M15-BFG', serial_number: 'AL-M15-6623', children_count: 0 },

    { id: 'ast-v201', tag: 'V-201', name: 'HP Separator V-201', description: 'High pressure 3-phase separator', taxonomy_level: 'equipment', parent_id: 'sys-sep', site: 'Site A — Offshore Platform Alpha', unit: 'Gas Processing', system: 'Separation', functional_location: 'ALPHA > GAS PROC > SEP', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'pressure_vessel', criticality: 'A', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'rbi', design_data: { design_pressure_bar: 95, design_temperature_c: 120, material_class: 'CS+CRA Clad', weight_kg: 45000 }, operating_context: { service_medium: 'Multiphase (Oil/Gas/Water)', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(2555), warranty_expiry: null, last_overhaul: d(730), condition_rating: 4, health_index: 93.1, rul_days: null, risk_priority: rpn(5, 1, 2), running_hours: 60000, mtbf_days: null, mttr_hours: 120, failure_count_ytd: 0, wo_count_ytd: 2, cost_ytd: 8400, manufacturer: 'Wärtsilä', model: 'SEP-3PH-60', serial_number: 'WRT-SEP-1122', children_count: 0 },

    { id: 'ast-v205', tag: 'V-205', name: 'LP Separator V-205', description: 'Low pressure 2-phase separator, gas/condensate', taxonomy_level: 'equipment', parent_id: 'sys-sep', site: 'Site A — Offshore Platform Alpha', unit: 'Gas Processing', system: 'Separation', functional_location: 'ALPHA > GAS PROC > SEP', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'pressure_vessel', criticality: 'B', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'rbi', design_data: { design_pressure_bar: 12, design_temperature_c: 80, material_class: 'CS', weight_kg: 18000 }, operating_context: { service_medium: 'Gas/Condensate', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(2555), warranty_expiry: null, last_overhaul: d(540), condition_rating: 3, health_index: 78.4, rul_days: 200, risk_priority: rpn(3, 3, 2), running_hours: 58000, mtbf_days: null, mttr_hours: 72, failure_count_ytd: 0, wo_count_ytd: 4, cost_ytd: 12800, manufacturer: 'Wärtsilä', model: 'SEP-2PH-30', serial_number: 'WRT-SEP-2205', children_count: 0 },

    { id: 'ast-hx405', tag: 'HX-405', name: 'Gas Cooler HX-405', description: 'Plate-fin gas cooler, compression intercooler', taxonomy_level: 'equipment', parent_id: 'sys-comp', site: 'Site A — Offshore Platform Alpha', unit: 'Gas Processing', system: 'Compression Train A', functional_location: 'ALPHA > GAS PROC > COMP-A', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'plate_fin_exchanger', criticality: 'B', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'rbi', design_data: { design_pressure_bar: 65, design_temperature_c: 120, material_class: 'Aluminium 6061', weight_kg: 4500 }, operating_context: { service_medium: 'Natural Gas', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(1825), warranty_expiry: null, last_overhaul: d(365), condition_rating: 3, health_index: 80.1, rul_days: 190, risk_priority: rpn(3, 2, 3), running_hours: 42000, mtbf_days: null, mttr_hours: 48, failure_count_ytd: 1, wo_count_ytd: 5, cost_ytd: 22400, manufacturer: 'Chart Industries', model: 'PF-6000', serial_number: 'CHT-PF-4405', children_count: 0 },

    { id: 'ast-tk801', tag: 'TK-801', name: 'Chemical Storage Tank TK-801', description: 'Chemical injection storage tank, corrosion inhibitor', taxonomy_level: 'equipment', parent_id: 'sys-chem', site: 'Site A — Offshore Platform Alpha', unit: 'Utilities', system: 'Chemical Injection', functional_location: 'ALPHA > UTIL > CHEM INJ', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'atmospheric_tank', criticality: 'C', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'pm_optimization', install_date: d(1460), warranty_expiry: null, last_overhaul: null, condition_rating: 4, health_index: 88.0, rul_days: null, risk_priority: rpn(2, 2, 2), running_hours: 35040, mtbf_days: null, mttr_hours: 8, failure_count_ytd: 0, wo_count_ytd: 2, cost_ytd: 3200, manufacturer: 'Enduro FRP', model: 'CIT-5000L', serial_number: 'END-CIT-8801', children_count: 0 },

    { id: 'ast-v602', tag: 'V-602', name: 'Knockout Drum V-602', description: 'Compressor suction knockout drum', taxonomy_level: 'equipment', parent_id: 'sys-comp', site: 'Site A — Offshore Platform Alpha', unit: 'Gas Processing', system: 'Compression Train A', functional_location: 'ALPHA > GAS PROC > COMP-A', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'pressure_vessel', criticality: 'D', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'pm_optimization', install_date: d(1825), warranty_expiry: null, last_overhaul: null, condition_rating: 5, health_index: 97.0, rul_days: null, risk_priority: rpn(2, 1, 1), running_hours: 43800, mtbf_days: null, mttr_hours: 8, failure_count_ytd: 0, wo_count_ytd: 1, cost_ytd: 1200, manufacturer: 'Nacional', model: 'KD-1500', serial_number: 'NAC-KD-9934', children_count: 0 },

    { id: 'ast-e401', tag: 'E-401', name: 'Fin Fan Cooler E-401', description: 'Air cooled heat exchanger, gas aftercooler', taxonomy_level: 'equipment', parent_id: 'sys-cool', site: 'Site A — Offshore Platform Alpha', unit: 'Utilities', system: 'Cooling System', functional_location: 'ALPHA > UTIL > COOL', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'air_cooled_exchanger', criticality: 'B', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'pm_optimization', install_date: d(1460), warranty_expiry: null, last_overhaul: d(365), condition_rating: 4, health_index: 85.3, rul_days: 200, risk_priority: rpn(3, 2, 2), running_hours: 35040, mtbf_days: null, mttr_hours: 24, failure_count_ytd: 0, wo_count_ytd: 4, cost_ytd: 9800, manufacturer: 'HTRI', model: 'AFC-8000', serial_number: 'HTRI-AFC-4456', children_count: 0 },

    // ── SITE B: Onshore Terminal ──
    { id: 'ast-p301', tag: 'P-301A', name: 'Transfer Pump P-301A', description: 'Crude transfer pump, tank farm to jetty', taxonomy_level: 'equipment', parent_id: 'sys-tf', site: 'Site B — Onshore Terminal', unit: 'Tank Farm', system: 'Transfer System', functional_location: 'BRAVO > TANK FARM > TRANSFER', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'centrifugal_pump', criticality: 'B', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'pm_optimization', install_date: d(730), warranty_expiry: d(-180), last_overhaul: null, condition_rating: 4, health_index: 90.1, rul_days: 310, risk_priority: rpn(3, 2, 1), running_hours: 12400, mtbf_days: 400, mttr_hours: 12, failure_count_ytd: 0, wo_count_ytd: 3, cost_ytd: 5600, manufacturer: 'KSB', model: 'Omega 350', serial_number: 'KSB-OM-7281', children_count: 0 },

    { id: 'ast-t101', tag: 'T-101', name: 'Crude Storage Tank T-101', description: 'Floating roof tank, 50000 bbl capacity', taxonomy_level: 'equipment', parent_id: 'sys-tf', site: 'Site B — Onshore Terminal', unit: 'Tank Farm', system: 'Storage', functional_location: 'BRAVO > TANK FARM > STORAGE', equipment_type: 'mechanical', equipment_class: 'static_pressure', equipment_category: 'floating_roof_tank', criticality: 'B', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'rbi', install_date: d(3650), warranty_expiry: null, last_overhaul: d(1095), condition_rating: 3, health_index: 77.8, rul_days: null, risk_priority: rpn(4, 2, 3), running_hours: 87600, mtbf_days: null, mttr_hours: 240, failure_count_ytd: 0, wo_count_ytd: 2, cost_ytd: 22400, manufacturer: 'TF Warren', model: 'FRT-50K', serial_number: 'TFW-FRT-0084', children_count: 0 },

    { id: 'ast-flr01', tag: 'FLR-01', name: 'HP Flare Tip FLR-01', description: 'High pressure flare tip assembly', taxonomy_level: 'equipment', parent_id: 'sys-flare', site: 'Site A — Offshore Platform Alpha', unit: 'Utilities', system: 'Flare System', functional_location: 'ALPHA > UTIL > FLARE', equipment_type: 'mechanical', equipment_class: 'safety', equipment_category: 'flare_tip', criticality: 'A', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'condition_based', install_date: d(2555), warranty_expiry: null, last_overhaul: d(365), condition_rating: 3, health_index: 79.4, rul_days: 150, risk_priority: rpn(5, 2, 3), running_hours: 60000, mtbf_days: null, mttr_hours: 168, failure_count_ytd: 0, wo_count_ytd: 1, cost_ytd: 4200, manufacturer: 'NAO Inc.', model: 'XP-500', serial_number: 'NAO-XP-3310', children_count: 0 },

    { id: 'ast-usp01', tag: 'USP-01', name: 'UPS System USP-01', description: 'Uninterruptible power supply, control room', taxonomy_level: 'equipment', parent_id: 'sys-elec', site: 'Site A — Offshore Platform Alpha', unit: 'Electrical', system: 'Essential Power', functional_location: 'ALPHA > ELEC > ESSENTIAL', equipment_type: 'electrical', equipment_class: 'electrical', equipment_category: 'ups_system', criticality: 'A', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'condition_based', install_date: d(1095), warranty_expiry: d(-365), last_overhaul: null, condition_rating: 4, health_index: 92.8, rul_days: 500, risk_priority: rpn(5, 1, 1), running_hours: 26280, mtbf_days: null, mttr_hours: 4, failure_count_ytd: 0, wo_count_ytd: 2, cost_ytd: 3800, manufacturer: 'Eaton', model: '93PM 80kW', serial_number: 'EAT-93PM-4421', children_count: 0 },

    { id: 'ast-c301', tag: 'C-301', name: 'Air Compressor C-301', description: 'Instrument air compressor, oil-free screw', taxonomy_level: 'equipment', parent_id: 'sys-air', site: 'Site A — Offshore Platform Alpha', unit: 'Utilities', system: 'Instrument Air', functional_location: 'ALPHA > UTIL > INST AIR', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'screw_compressor', criticality: 'B', criticality_method: 'manual', status: 'standby', maintenance_strategy: 'pm_optimization', install_date: d(1460), warranty_expiry: null, last_overhaul: d(270), condition_rating: 4, health_index: 87.6, rul_days: 250, risk_priority: rpn(3, 2, 2), running_hours: 18200, mtbf_days: 360, mttr_hours: 8, failure_count_ytd: 0, wo_count_ytd: 5, cost_ytd: 11200, manufacturer: 'Atlas Copco', model: 'ZR 250', serial_number: 'AC-ZR-6678', children_count: 0 },

    { id: 'ast-sd01', tag: 'SD-01', name: 'ESD Valve SD-01', description: 'Emergency shutdown valve, wellhead isolation', taxonomy_level: 'equipment', parent_id: 'sys-safety', site: 'Site A — Offshore Platform Alpha', unit: 'Safety Systems', system: 'ESD System', functional_location: 'ALPHA > SAFETY > ESD', equipment_type: 'safety_system', equipment_class: 'safety', equipment_category: 'esd_valve', criticality: 'A', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'condition_based', install_date: d(2555), warranty_expiry: null, last_overhaul: d(365), condition_rating: 4, health_index: 95.0, rul_days: null, risk_priority: rpn(5, 1, 1), running_hours: 60000, mtbf_days: null, mttr_hours: 8, failure_count_ytd: 0, wo_count_ytd: 4, cost_ytd: 6200, manufacturer: 'Cameron', model: 'Type F', serial_number: 'CAM-TF-1108', children_count: 0 },

    { id: 'ast-mot101', tag: 'MOT-101A', name: 'Motor MOT-101A', description: 'Electric motor driver for P-101A, 500kW', taxonomy_level: 'equipment', parent_id: 'sys-export', site: 'Site A — Offshore Platform Alpha', unit: 'Crude Oil Processing', system: 'Export System', functional_location: 'ALPHA > CRUDE > EXPORT', equipment_type: 'electrical', equipment_class: 'electrical', equipment_category: 'induction_motor', criticality: 'A', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'condition_based', design_data: { rated_power_kw: 500, weight_kg: 1800 }, operating_context: { operating_mode: 'continuous', environment: 'offshore' }, install_date: d(1460), warranty_expiry: null, last_overhaul: d(90), condition_rating: 4, health_index: 89.5, rul_days: 240, risk_priority: rpn(4, 2, 2), running_hours: 34500, mtbf_days: 350, mttr_hours: 24, failure_count_ytd: 0, wo_count_ytd: 3, cost_ytd: 8200, manufacturer: 'ABB', model: 'M3BP 355', serial_number: 'ABB-M3-5567', children_count: 0 },

    { id: 'ast-crane01', tag: 'CR-01', name: 'Pedestal Crane CR-01', description: 'Offshore pedestal crane, 60T SWL', taxonomy_level: 'equipment', parent_id: 'sys-struct', site: 'Site A — Offshore Platform Alpha', unit: 'Structural', system: 'Lifting Equipment', functional_location: 'ALPHA > STRUCT > LIFTING', equipment_type: 'structural', equipment_class: 'structural', equipment_category: 'pedestal_crane', criticality: 'A', criticality_method: 'manual', status: 'operating', maintenance_strategy: 'condition_based', design_data: { weight_kg: 85000 }, install_date: d(3650), warranty_expiry: null, last_overhaul: d(365), condition_rating: 3, health_index: 80.2, rul_days: 180, risk_priority: rpn(5, 2, 2), running_hours: 14600, mtbf_days: null, mttr_hours: 48, failure_count_ytd: 1, wo_count_ytd: 6, cost_ytd: 56000, manufacturer: 'NOV', model: 'PSC-60T', serial_number: 'NOV-PSC-2201', children_count: 0 },

    { id: 'ast-p401', tag: 'P-401', name: 'Seawater Lift Pump P-401', description: 'Vertical caisson seawater lift pump', taxonomy_level: 'equipment', parent_id: 'sys-sw', site: 'Site A — Offshore Platform Alpha', unit: 'Utilities', system: 'Seawater System', functional_location: 'ALPHA > UTIL > SEAWATER', equipment_type: 'mechanical', equipment_class: 'rotating', equipment_category: 'vertical_pump', criticality: 'B', criticality_method: 'calculated', status: 'under_maintenance', maintenance_strategy: 'rcm', design_data: { rated_power_kw: 250, design_pressure_bar: 15, material_class: 'Super Duplex', weight_kg: 5600 }, operating_context: { service_medium: 'Seawater', operating_mode: 'continuous', environment: 'offshore' }, install_date: d(2190), warranty_expiry: null, last_overhaul: d(730), condition_rating: 2, health_index: 45.3, rul_days: 20, risk_priority: rpn(3, 5, 3), running_hours: 50000, mtbf_days: 150, mttr_hours: 72, failure_count_ytd: 4, wo_count_ytd: 15, cost_ytd: 98400, manufacturer: 'Sulzer', model: 'VTP-8/6', serial_number: 'SUL-VTP-4490', children_count: 0 },

    { id: 'ast-strn01', tag: 'STN-01', name: 'Strainer STN-01', description: 'Y-strainer, instrument air line', taxonomy_level: 'equipment', parent_id: 'sys-air', site: 'Site A — Offshore Platform Alpha', unit: 'Utilities', system: 'Instrument Air', functional_location: 'ALPHA > UTIL > INST AIR', equipment_type: 'mechanical', equipment_class: 'piping', equipment_category: 'strainer', criticality: 'E', criticality_method: 'calculated', status: 'operating', maintenance_strategy: 'run_to_failure', install_date: d(1460), warranty_expiry: null, last_overhaul: null, condition_rating: 4, health_index: 90.0, rul_days: null, risk_priority: rpn(1, 2, 1), running_hours: 35040, mtbf_days: null, mttr_hours: 2, failure_count_ytd: 0, wo_count_ytd: 0, cost_ytd: 0, manufacturer: 'Spirax Sarco', model: 'Fig. 14', serial_number: 'SS-14-9012', children_count: 0 },
];

export const INITIAL_HIERARCHY: HierarchyNode[] = [
    { id: 'ent-cainergy', name: 'Cainergy E&P', code: 'CAINERGY', level: 'enterprise', parent_id: null, description: 'Enterprise root', children_count: 2 },
    { id: 'site-alpha', name: 'Offshore Platform Alpha', code: 'ALPHA', level: 'site', parent_id: 'ent-cainergy', description: 'Deepwater production platform', children_count: 7 },
    { id: 'site-bravo', name: 'Onshore Terminal Bravo', code: 'BRAVO', level: 'site', parent_id: 'ent-cainergy', description: 'Crude oil export terminal', children_count: 1 },
    { id: 'unit-gasproc', name: 'Gas Processing', code: 'GAS-PROC', level: 'unit', parent_id: 'site-alpha', description: 'Gas compression, separation, dehydration', children_count: 2 },
    { id: 'unit-power', name: 'Power Generation', code: 'POWER-GEN', level: 'unit', parent_id: 'site-alpha', description: 'Main and emergency power', children_count: 1 },
    { id: 'unit-crude', name: 'Crude Oil Processing', code: 'CRUDE', level: 'unit', parent_id: 'site-alpha', description: 'Crude separation, stabilization, export', children_count: 2 },
    { id: 'unit-util', name: 'Utilities', code: 'UTIL', level: 'unit', parent_id: 'site-alpha', description: 'Air, cooling, seawater, chemicals, flare', children_count: 5 },
    { id: 'unit-elec', name: 'Electrical', code: 'ELEC', level: 'unit', parent_id: 'site-alpha', description: 'Power distribution, MCC, UPS', children_count: 1 },
    { id: 'unit-safety', name: 'Safety Systems', code: 'SAFETY', level: 'unit', parent_id: 'site-alpha', description: 'ESD, F&G, blowdown', children_count: 1 },
    { id: 'unit-struct', name: 'Structural', code: 'STRUCT', level: 'unit', parent_id: 'site-alpha', description: 'Structural steelwork, cranes, helideck', children_count: 1 },
    { id: 'unit-wi', name: 'Water Injection', code: 'WATER-INJ', level: 'unit', parent_id: 'site-alpha', description: 'Injection water treatment and pumping', children_count: 1 },
    { id: 'unit-tf', name: 'Tank Farm', code: 'TANK-FARM', level: 'unit', parent_id: 'site-bravo', description: 'Crude storage and transfer', children_count: 2 },
    { id: 'sys-comp', name: 'Compression Train A', code: 'COMP-A', level: 'system', parent_id: 'unit-gasproc', description: '1st and 2nd stage compression', children_count: 3 },
    { id: 'sys-sep', name: 'Separation', code: 'SEP', level: 'system', parent_id: 'unit-gasproc', description: 'HP/LP separation', children_count: 2 },
    { id: 'sys-power', name: 'Main Power', code: 'MAIN-PWR', level: 'system', parent_id: 'unit-power', description: 'Gas turbine generators', children_count: 1 },
    { id: 'sys-export', name: 'Export System', code: 'EXPORT', level: 'system', parent_id: 'unit-crude', description: 'Crude export pumping', children_count: 2 },
    { id: 'sys-dist', name: 'Overhead System', code: 'OVERHEAD', level: 'system', parent_id: 'unit-crude', description: 'Crude distillation overhead', children_count: 1 },
    { id: 'sys-cool', name: 'Cooling System', code: 'COOL', level: 'system', parent_id: 'unit-util', description: 'Air and water cooling', children_count: 1 },
    { id: 'sys-air', name: 'Instrument Air', code: 'INST-AIR', level: 'system', parent_id: 'unit-util', description: 'Instrument and utility air', children_count: 2 },
    { id: 'sys-sw', name: 'Seawater System', code: 'SEAWATER', level: 'system', parent_id: 'unit-util', description: 'Seawater lift and distribution', children_count: 1 },
    { id: 'sys-flare', name: 'Flare System', code: 'FLARE', level: 'system', parent_id: 'unit-util', description: 'HP/LP flare systems', children_count: 1 },
    { id: 'sys-chem', name: 'Chemical Injection', code: 'CHEM-INJ', level: 'system', parent_id: 'unit-util', description: 'Corrosion inhibitor, scale, demulsifier', children_count: 1 },
    { id: 'sys-elec', name: 'Essential Power', code: 'ESSENTIAL', level: 'system', parent_id: 'unit-elec', description: 'UPS, battery, emergency lighting', children_count: 1 },
    { id: 'sys-safety', name: 'ESD System', code: 'ESD', level: 'system', parent_id: 'unit-safety', description: 'Emergency shutdown valves and logic', children_count: 1 },
    { id: 'sys-struct', name: 'Lifting Equipment', code: 'LIFTING', level: 'system', parent_id: 'unit-struct', description: 'Cranes and davits', children_count: 1 },
    { id: 'sys-wi', name: 'Injection System', code: 'INJ-SYS', level: 'system', parent_id: 'unit-wi', description: 'High-pressure injection pumping', children_count: 1 },
    { id: 'sys-tf', name: 'Transfer System', code: 'TRANSFER', level: 'system', parent_id: 'unit-tf', description: 'Tank farm pumping and transfer', children_count: 1 },
    { id: 'sys-storage', name: 'Storage', code: 'STORAGE', level: 'system', parent_id: 'unit-tf', description: 'Crude storage tanks', children_count: 1 },
];

export const MOCK_FAILURE_EVENTS: FailureEvent[] = [
    { id: 'fe-001', asset_id: 'ast-k601', wo_id: 'WO-2026-001', start_time: d(95), end_time: d(93.5), downtime_hours: 36, failure_mode: 'abnormal_vibration', failure_cause: 'wear', remedy: 'replace', severity: 3, description: 'High vibration on DE bearing — replaced tilting pad bearing assembly', cost: 42000, detected_by: 'condition_monitoring', is_planned: false },
    { id: 'fe-002', asset_id: 'ast-k601', wo_id: 'WO-2026-008', start_time: d(32), end_time: d(30), downtime_hours: 48, failure_mode: 'leakage_external', failure_cause: 'fatigue', remedy: 'repair', severity: 4, description: 'Process gas leak at discharge flange — gasket fatigue failure', cost: 18500, detected_by: 'operator', is_planned: false },
    { id: 'fe-003', asset_id: 'ast-k601-brg', wo_id: 'WO-2026-001', start_time: d(95), end_time: d(94), downtime_hours: 24, failure_mode: 'overheating', failure_cause: 'wear', remedy: 'replace', severity: 3, description: 'Bearing pad temperature exceeded 120°C — rotor contact marks on tilting pads', cost: 32000, detected_by: 'alarm', is_planned: false },
    { id: 'fe-004', asset_id: 'ast-gt301', wo_id: 'WO-2026-012', start_time: d(180), end_time: d(177), downtime_hours: 72, failure_mode: 'low_output', failure_cause: 'contamination', remedy: 'clean', severity: 3, description: 'Compressor fouling — output degraded 8% — online wash ineffective, offline wash performed', cost: 58000, detected_by: 'condition_monitoring', is_planned: false },
    { id: 'fe-005', asset_id: 'ast-p102', wo_id: 'WO-2026-003', start_time: d(280), end_time: d(279.5), downtime_hours: 12, failure_mode: 'leakage_external', failure_cause: 'wear', remedy: 'replace', severity: 2, description: 'Mechanical seal failure — minor process leak contained', cost: 8200, detected_by: 'operator', is_planned: false },
    { id: 'fe-006', asset_id: 'ast-p102', wo_id: 'WO-2026-009', start_time: d(160), end_time: d(159.5), downtime_hours: 12, failure_mode: 'abnormal_vibration', failure_cause: 'wear', remedy: 'repair', severity: 2, description: 'Impeller imbalance — cavitation damage on eye', cost: 15600, detected_by: 'condition_monitoring', is_planned: false },
    { id: 'fe-007', asset_id: 'ast-p102', wo_id: 'WO-2026-015', start_time: d(45), end_time: d(44.5), downtime_hours: 12, failure_mode: 'leakage_external', failure_cause: 'corrosion', remedy: 'replace', severity: 3, description: 'Casing gasket corrosion — replaced with upgraded super duplex gasket', cost: 22000, detected_by: 'inspection', is_planned: false },
    { id: 'fe-008', asset_id: 'ast-p401', wo_id: 'WO-2026-004', start_time: d(310), end_time: d(307), downtime_hours: 72, failure_mode: 'abnormal_vibration', failure_cause: 'corrosion', remedy: 'overhaul', severity: 4, description: 'Severe pitting on impeller — full pump overhaul required', cost: 35000, detected_by: 'condition_monitoring', is_planned: false },
    { id: 'fe-009', asset_id: 'ast-p401', wo_id: 'WO-2026-007', start_time: d(220), end_time: d(217), downtime_hours: 72, failure_mode: 'leakage_internal', failure_cause: 'erosion', remedy: 'replace', severity: 3, description: 'Wear ring clearance exceeded — internal recirculation', cost: 18400, detected_by: 'condition_monitoring', is_planned: false },
    { id: 'fe-010', asset_id: 'ast-p401', wo_id: 'WO-2026-011', start_time: d(120), end_time: d(117), downtime_hours: 72, failure_mode: 'failure_to_start', failure_cause: 'electrical_fault', remedy: 'repair', severity: 4, description: 'Motor winding insulation failure — VFD overcurrent trip', cost: 28000, detected_by: 'alarm', is_planned: false },
    { id: 'fe-011', asset_id: 'ast-p401', wo_id: 'WO-2026-016', start_time: d(20), end_time: d(17), downtime_hours: 72, failure_mode: 'leakage_external', failure_cause: 'corrosion', remedy: 'replace', severity: 3, description: 'Column pipe flange leak — MIC (microbiologically induced corrosion)', cost: 17000, detected_by: 'operator', is_planned: false },
    { id: 'fe-012', asset_id: 'ast-hx405', wo_id: 'WO-2026-010', start_time: d(150), end_time: d(148), downtime_hours: 48, failure_mode: 'leakage_internal', failure_cause: 'corrosion', remedy: 'repair', severity: 3, description: 'Tube bundle leak — hydro test confirmed 2 tube failures, plugged', cost: 22400, detected_by: 'inspection', is_planned: false },
    { id: 'fe-013', asset_id: 'ast-crane01', wo_id: 'WO-2026-013', start_time: d(200), end_time: d(198), downtime_hours: 48, failure_mode: 'erratic_output', failure_cause: 'electrical_fault', remedy: 'replace', severity: 3, description: 'Slew drive encoder failure — erratic rotation control', cost: 56000, detected_by: 'operator', is_planned: false },
    { id: 'fe-014', asset_id: 'ast-k601', start_time: d(420), end_time: d(418.5), downtime_hours: 36, failure_mode: 'abnormal_vibration', failure_cause: 'wear', remedy: 'replace', severity: 3, description: 'NDE bearing high temperature — replaced', cost: 38000, detected_by: 'alarm', is_planned: false },
    { id: 'fe-015', asset_id: 'ast-gt301', start_time: d(540), end_time: d(537), downtime_hours: 72, failure_mode: 'overheating', failure_cause: 'contamination', remedy: 'overhaul', severity: 4, description: 'Hot section distress — T5 spread exceeded limits', cost: 185000, detected_by: 'condition_monitoring', is_planned: false },
    { id: 'fe-016', asset_id: 'ast-p401', start_time: d(480), end_time: d(477), downtime_hours: 72, failure_mode: 'abnormal_vibration', failure_cause: 'wear', remedy: 'overhaul', severity: 3, description: 'Bearing failure — full rebuild', cost: 24000, detected_by: 'alarm', is_planned: false },
    { id: 'fe-017', asset_id: 'ast-p102', start_time: d(400), end_time: d(399.5), downtime_hours: 12, failure_mode: 'leakage_external', failure_cause: 'wear', remedy: 'replace', severity: 2, description: 'Mechanical seal leak — standard replacement', cost: 6800, detected_by: 'operator', is_planned: false },
];
